language: ruby
before_install:
  - gem update --system
  - gem --version
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
script: bundle exec rspec spec
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: rbx-18mode
    - rvm: ruby-head
